# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lchaillo <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/08 11:44:28 by lchaillo          #+#    #+#              #
#    Updated: 2017/11/08 13:25:03 by lchaillo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
FLAG = -Wall -Wextra -Werror
NAME = ft_display_file

all :
	$(CC) $(FLAG) ft_putstr.c ft_display.c ft_display_file.c -I inlude.h -o $(NAME)

clean :

fclean : clean
	/bin/rm ft_display_file
